4lesson
NastyaKoval/HTML pull request #5
Opened 2022-09-17 21:12 UTC by NastyaKoval

2022-09-18 07:19 UTC, Gaurrus requested changes

2022-09-18 07:19 UTC, Gaurrus commented on CSS/HW/4/4.1/Задание.html
> +            border-right-color: red;
margin-bottom: 20px; чисто для эстетики)

2022-09-18 07:19 UTC, Gaurrus commented on CSS/HW/4/4.4/таблица.html
> +        table {
у таблицы есть свойство empty-cells

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/Pagination.html
> +*{margin:0;
если можно, то пишите все правила стилий однотипно)
обычно пишут
 ```
a:hover {
	background-color: #ff6c00;
}
```

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/Pagination.html
> +*{margin:0;
с отступом и переходом на следующую строку. В общем что бы везде было красивенько и одинаково)

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/Pagination.html
> +#Pagination
селекторы обычно пишут через дефис с маленькой буквы.
да и тут я думаю не за чем использовать селектор по id, можно обойтись классами
таким образом тут будет селектор 
```
.pagination

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/Pagination.html
> +   <a href="#"> &laquo;Previous</a>
опять что-то кривенько

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/Pagination.html
> +</html>
что то не очень то похоже получилось... на фото примера в задании
попробуйте согласно темы использовать свойство display
например для пунктов меню можно использовать display: inline-block
и тогда можно внутренние отступы задать для элементов

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/left-menu.html
> +
тоже криво написано

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/5/5.4/left-menu.html
> +</html>
тоже не похоже на фото с задания, нужно убрать подчеркивание текста и сделать его жирным

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +
пробел лишний

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +            border: 2px solid;
а цвет бордера где?

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +            border-color: rgb(13, 13, 237);
ааа вот он... напишите в одном свойстве это всё)

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +            width: auto;
а это не лишнее?

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +</html>
не похоже. У вас текст вверху блока, а в примере текст по высоте в центре

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +            height: 30px;
попробйте не задавать конкретную высоту и ширину, а сыграть падингами и высотой строки.
например если у вас высота 30px, то вполне можно её сделать высотой строки в 14px и отступами в 8px

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.1.html
> +        .div1{
название классов какое-нибудь более осмысленное хотелось бы)

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.2.html
> +</html>
не похоже. У вас текст вверху блока, а в примере текст по высоте в центре

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.3.html
> +</html>
тоже самое это у вас наверно везде, нужно 1 раз исправить и перенести на всё)

2022-10-04 07:04 UTC, ValadzkoAliaksei commented on CSS/HW/6/6.7.html
> +</html>
что-то оно не отличается от 6.6 визуально) а должно...

2022-10-18 11:50 UTC, merged